# This is a library function, you can't modify it.
def get_payments_storage():
    """
    @returns an instance of
    https://docs.python.org/3/library/io.html#io.BufferedWriter
    """
    # Sample implementation to make the code run in coderpad.
    # Do not rely on this exact implementation.
    return open('/dev/null', 'wb')


# This is a library function, you can't modify it.
def stream_payments_to_storage(storage):
    """
    Loads payments and writes them to the `storage`.
    Returns when all payments have been written.
    @parameter `storage`: is an instance of
    https://docs.python.org/3/library/io.html#io.BufferedWriter
    """
    # Sample implementation to make the code run in coderpad.
    # Do not rely on this exact implementation.
    for i in range(10):
        storage.write(bytes([1, 2, 3, 4, 5]))


def process_payments():
    """
    Modify `process_payments()` to print the checksum of data
    generated by the `stream_payments_to_storage()` call.
    """

    class ChecksumStorageWrapper:
        def __init__(self, storage):
            self.storage = storage
            self.checksum = 0

        def write(self, buffer):
            # The checksum is implemented as a simple arithmetic sum of bytes.
            self.checksum += sum(buffer)
            self.storage.write(buffer)

    storage = get_payments_storage()
    checksum_storage = ChecksumStorageWrapper(storage)
    stream_payments_to_storage(checksum_storage)
    print(f"Checksum: {checksum_storage.checksum}")


process_payments()
